3drepo/3drepobouncer

bouncer/src/repo/core/model/collection/repo_scene.h
bouncer/src/repo/error_codes.h
bouncer/src/repo/manipulator/repo_manipulator.cpp

This is to allow a better error message when the revision bson exceeds the mongo maximum size (16MB)
I don't have a model to test this so please check my maths:
1 UUID is 128bit (aka 16B)
the maximum amount of UUIDs we can hold in 16MB is 16*1024*1024 / 16 = 1048576
so I've set the limit to 1030000 (to give ~290KB for random stuff)

ISSUE #251 impose a maximum node limit and return error if exceeded

---

tools/bouncer_worker/bouncer_worker.js
tools/bouncer_worker/importToy.js
tools/bouncer_worker/package.json

This PR fixes #253 
**Problem:**
Sample project federation's groups doesn't always work.
**Why:**
As it stands, the model ID within the object array of groups are updated when we call importToy on the federation model. This is done by looking through the database of the sub models listed and see, for each ID,whether we can find the objects indicated within the submodels, if we find one, then we rename the obj.model to that sub model, otherwise, we leave it as federation ID.
This is a problem because:
- The process can happen before the sub model has been fully imported, thus the objects may not exist in the subModel
- The process can happen before the federation has been federated.
**Fix:**
- Instead of looking for the objects, we store a mapping of old model ID to model name, so we can …

Issue 253 Fix sample project

---

tools/bouncer_worker/package.json

This resolves #258 
Winston has had a major version bump, breaking our bouncer worker on new installs

ISSUE #258 fix winston version

---

client/src/functions.cpp
tools/bouncer_worker/bouncer_worker.js

This fixes #260 and https://github.com/3drepo/3drepo.io/issues/1042
Problem Pavol had was because we only re-generate the tree for the latest revision (regeneration of tree is needed to ensure the modelID and the teamspace name is correct), meaning the tree is effectively broken if you try to load any older revisions.
This is fixed by ensuring we generate all trees for all revisions when we import the sample project.

Issue 260 - ensure sample project generates trees for all revisions

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_ifc_utils_geometry.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_assimp.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_assimp.h

This resolves #255 
**Description**
Set a bunch of normalisation values for shininess (as different formats would come in with different values) so it's always 0-1.
This should make newly uploaded models look better.

Issue 255 - Enhance shininess

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_ifc_utils_geometry.cpp

This resolves #276 
Halving the specularity strength and shininess value to reduce crazy mirrored effect on IFC models

Issue 276 - IFC shininess tweaks

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_dgn.cpp

- should return no mesh found error message instead of unknown error on dgn imports that failed with no meshes.
I didn't have any files with no mesh (tried to get one from the business guys but no luck yet), so I only tested this by hacking the if condition...

Issue 279 - return no mesh error instead of unknown error if no mesh from dgn

---

tools/bouncer_worker/exportToy.py

I forgot to change the script to export risks/views from the toy project federation, so all the toy projects imported had no risks/views.
`exportToy.js` is used on a set of sample models to do a mongoexport to retrieve mongo dumps for future toy project imports
There's an update to the zip file of the export, also relies on a change on https://github.com/3drepo/3drepo.io/issues/1263 to see the risks

ISSUE #289 toy project fix : export risks/views

---

bouncer/src/repo/core/model/bson/repo_node_mesh.cpp
bouncer/src/repo/core/model/collection/repo_scene.cpp
bouncer/src/repo/manipulator/modeloptimizer/repo_optimizer_trans_reduction.cpp
bouncer/src/repo/manipulator/modeloptimizer/repo_optimizer_trans_reduction.h
bouncer/src/repo/repo_controller.h

- Reduced 4 getChildren/getChildrenByType calls to 1 getChildren call and 1 loop to filter for type.
- Removed the whole weird cache thing
-  Ensure meshNodes don't bother with applying transformation if the matrix is an identity
- Removed an iterator in RepoScene in favour of doing it inside an already existing loop

Issue 298 - Speed up optimiser

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_ifc_utils_parser.cpp

- No longer create a transformation node for IfcComplexProperty
- No longer traverse through the children of IfcComplexProperty
The file that killed the production box due to out of memory after running for 12+hrs now finishes within 2mins.

Issue 310 - Do not try to traverse children of IfcComplexProperty

---

bouncer/src/repo/core/model/bson/repo_bson.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_oda.cpp
tools/bouncer_worker/bouncer_worker.js

- Seg faults were happening due to mismatched lengths of vertices and UVs. This is caused by a condition where we add vertices to the mesh was not adding the UVs
- Also changed some of the includes to be relative paths (the rule is relative if it's within the library, and in `""`, only external libraries should be from root of library path and in `<>`)
- try catch block added within metadata calls to maximise the amount of metadata we'll get.
- According to [this](https://github.com/lerna/lerna/issues/213) using spawn instead of exec should no longer run into `ERR_CHILD_PROCESS_STDIO_MAXBUFFER` problems

Issue 317 - RVT fix

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.h

this fixes #326 
- Adding another metadata property to the ignore list
- moved the list into the `cpp` instead of `h` to reduce compilation time on modification

ISSUE #326 add another property to metadata ignore list.

---

.gitignore
bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
bouncer/src/repo/core/model/bson/repo_bson_factory.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.h

- Use map instead of pair<vector, vector> to ensure no duplicates
- Read into an param pointer to read the value instead of returning the pointer ID if available.
- after the above, duplicated values seems to have the same data (so far)

Issue 332 - RVT meta fix

---

.travis.yml
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.h

The program now takes a env var, `ODA_CSV_LOCATION`, to point to the folder that has the CSV folder (typically ODA's exe folder.)

Issue 344 - fix revit metadata

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp

this fixes #389 
use int64_t instead of int32_t to store indexing, as they can get beyond 2GB.

ISSUE #389 use int64_t to address indices

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.h

This resolves #393 
- ensure the object is removed from the visibility state cache if the visibility resets/changes
- transformation of the final state is applied and assumed to be the default position. An Inverse of the matrix is applied when the transformation resets.

Issue 393 - Synchro fixes

---

bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_src.cpp
bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_src.h

Compresses the binary buffer section of the SRC file using zlib with Boost stream filters. Indicates this to the application by adjusting the SRC header magic value (as this is no longer a standards compliant SRC).

Fixes Issue 406

---

bouncer/src/repo/lib/repo_log.cpp
tools/bouncer_worker/README.md
tools/bouncer_worker/package.json
tools/bouncer_worker/src/lib/config.js
tools/bouncer_worker/src/lib/messageDecoder.js
tools/bouncer_worker/src/lib/queueHandler.js
tools/bouncer_worker/src/lib/utils.js
tools/bouncer_worker/src/queues/common.js
tools/bouncer_worker/src/queues/jobQueueHandler.js
tools/bouncer_worker/src/queues/modelQueueHandler.js
tools/bouncer_worker/src/queues/unityQueueHandler.js
tools/bouncer_worker/src/tasks/unityEditor.js

This fixes #428
- tasks should no longer get stuck in the queue due to instruction file missing
- shared_dir and log_dir are checked at init, process will exit if they do not exist
- Changed unity editor call to depict the full name of unity.log and run_unity.log
- add logic to wait for a task in _exitAfter_ mode if the queue is empty
- introduced 2 new config variables:
- `pollingIntervalMS` In _exitAfter_ mode, the number of ms to wait inbetween polling the queue for tasks (default: 10000)                                                                                                                                                     
- `maxWaitTimeMS` In _exitAfter_ mode, the maximum wait time for a task before exiting the process (default: 300000 - aka 5mins)

Issue 428 unhandled promise fixes + unity queue improvement

---

tools/bouncer_worker/src/tasks/importToy.js

This fixes #433
- added missing await keyword on the model settings query. This was the cause for federation not being able to figure out submodel IDs to map to when we import the groups
- toy federation groups should function like normal

ISSUE #433 fix normal groups in sample federation

---

bouncer/src/repo/manipulator/modelutility/repo_scene_manager.cpp

This fixes #443 
`SceneManager::commitScene` decides whether to generate SRCs based on `shouldGenerateSrcFiles`. This method checks for meshes, but does not discriminate primitive type. This PR updates that check to make it explicit.
Note that due to the way the srcAssets.json is generated, models with lines will show errors on loading into Unreal (404s for the missing line supermesh srcs). It is safe to ignore these until they can be fixed properly (by updating, io, bouncer or the plugin).

Issue 443 - Pure 2D Lines Model Import Failure

---

bouncer/src/repo/core/model/collection/repo_scene.cpp

This fixes #445
- Shrunk all RepoNodes before committing. The problem seems to be mongo driver dealing with binary data inside the bson object.
- test case in the issue should now work

ISSUE #445 fix on .bim file crashing out of bouncer

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/CMakeLists.txt
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/vertex_map.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/vertex_map.h

This fixes #432. 
When adding faces, the GeometryCollector class attempts to reference existing vertices if possible, before adding new ones, but the previous implementation only considered vertices and an optional normal. This meant texture coordinates may be mismatched, and there was a whole second pathway for lines.
This PR adds a new VertexMap class that performs vertex buffer construction & referencing, updates the GeometryCollector class to use this, and do to so through one addFace overload.

ISSUE #432 - Vertex Referencing in GeometryCollector

---

.travis.yml

This fixes #395
- added new prebuilt libraries to run on focal fossa
- This runs on the default version of GCC/G++ (9.3), boost (1.71), OpenSSL (I forgot exact version... 1.1.* instead of 1.0.2).
- which means I've recompiled every external library with those versions.... yay.

Issue 395 get travis to run on focal fossa

---

tools/bouncer_worker/package.json
tools/bouncer_worker/src/tasks/importToy.js

This fixes #460
- version bump mongo driver
- use `replaceOne` instead of `updateOne` as updateOne no longer let you replace the whole document
- toy model (only functionality that uses the mongo driver) should still work

ISSUE #460 update mongodb (nodejs) driver

---

.travis.yml
test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo/manipulator/modelconvertor/import/ut_repo_model_import_synchro.cpp
test/src/unit/repo_test_database_info.h

This fixes #480
This only contain changes for tests, bulk of the change is in https://github.com/3drepo/SynchroReader/issues/5
- 6.2 is no longer supported and it will crash
- 6.3 should work as before
- 6.4 should now be supported

ISSUE #480 changes for synchro 6.4

---

tools/bouncer_worker/package.json
tools/bouncer_worker/src/lib/runCommand.js

This fixes ##496
`spawn.kill()` seems to have stopped working on v14. using `tree-kill` instead.

Issue 496 - fix killing process after timeout

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_ifc_utils_parser.cpp

This fixes #505
- rework how `IfcDerivedUnit` is treated, which should support every type of unit we know how to support
- The file in question has an invalid IFC2x3 schema, where `Edition` in `IfcClassification` is omitted. This breaks the whole tree due to how we're catching the error. 2 fixes here:
- check the argument is not null before we access the value
- put a try/catch around the part we recurse `childrenElements` (we have it on `extraChildren`, but for some reason it's missing on this one)
- file in question should now get processed.
NOTE: It still return with missing nodes (which is not investigated and it's possible that it is resolved in #478  ,) but it should no longer fail without geometry.

ISSUE #505 couple IFC bug fixes

---

bouncer/src/repo/core/handler/repo_database_handler_mongo.cpp
bouncer/src/repo/core/handler/repo_database_handler_mongo.h
bouncer/src/repo/lib/repo_config.cpp
bouncer/src/repo/lib/repo_config.h
bouncer/src/repo/manipulator/repo_manipulator.cpp
bouncer/src/repo/manipulator/repo_manipulator.h
bouncer/src/repo/repo_controller.cpp
bouncer/src/repo/repo_controller_internal.cpp.inl
client/src/functions.cpp
client/src/functions.h
client/src/main.cpp
tools/admin/bouncerTool.cpp
tools/admin/functions.cpp
tools/admin/functions.h

This fixes #524
- Add an option to read database info from a connection string
- old configurations should still work as before
- replacing `dbHost` and `dbPort` with `connectionString` should also work

Issue 524 - replica set connection support

---

bouncer/src/repo/repo_controller.cpp
wrapper/src/c_sharp_wrapper.cpp
wrapper/src/c_sharp_wrapper.h
wrapper/src/repo_csharp_interface.cpp
wrapper/src/repo_csharp_interface.h
wrapper_test/src/unit/ut_repo_csharp_interface.cpp

This fixes #532
- changed raw pointer to shared_ptr so it will call the deconstructor prior to exiting
- replicaset connection should no longer time out

ISSUE #531 fix replicaSet connection when processing models through bouncerwrapper

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.cpp
client/src/functions.cpp

This fixes #529
- we're passing a pointer to config instead of the actual config, which seems to result in erroneous config data.
- passing in `importAnimations: false` should now ignore any transformation instructions

ISSUE #529 fix animation flag

---

tools/bouncer_worker/src/lib/config.js
tools/bouncer_worker/src/tasks/importToy.js

This fixes #543
- automatically generate `connectionString` (if undefined) when we initialise the config file 
- connection to mongo for `importToy` features now connect using `connectionString`
- import toy should work:
- when mongo connection string is given in the config instead of host and port
- when  host and port are defined instead of mongo connection string

ISSUE #543 fix connections for import toy

---

bouncer/src/repo/repo_controller_internal.cpp.inl
test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo/ut_repo_controller.cpp

This fixes #558
- do not overwrite owner when we can't find credentials (not really related to model upload to begin with! Only put in anon. user if owner is not provided.
- should work as usual, with the bug resolved for connections based on connection string

Issue 558 - do not overwrite author with credentials

---

bouncer/src/repo/lib/repo_log.cpp

This fixes #560
- add a console logger when we instantiate RepoLog
- bouncer should now produce the log on console as well as file

ISSUE #560 add a console log to std::cout at instantiation

---

client/src/functions.cpp

This fixes #586
This requires https://github.com/3drepo/3drepo.io/issues/3436
Bouncer will now read in the revId from the federation request data if available
problem described in the issue should no longer happen

ISSUE #586 pass through the specified revision id if available

---

ifcUtils/repo_ifc_utils_tree_parser.cpp

This fixes #580
- instead of getting PSets from IFCElementType, we get it from IfcTypeObject instead so we can support IfcObjectType as well.
- Ignore `IfcPropertyDefinition` for now as this would require us supporting turning element properties of IfcTypeObject into metadata.
- we should see metadata being extracted from classes such as IFCDoorStyles

Issue 580 - retrieve psets from IfcTypeObject

---

.travis.yml
bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_asset.cpp

This fixes #623
2nd part of the solution to https://github.com/3drepo/3drepo.io/issues/4212
- aggregate all unity json mappings into a single and store it as `<rev_id>/supermeshes.json`
- should work as expected
- 3drepo.io should no longer need to generate this file on the fly for new model uploads

ISSUE #623 construct the supermesh cache file in bouncer

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_manager.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.h
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_units.h
test/src/unit/repo/manipulator/modelconvertor/import/ut_repo_model_import_synchro.cpp

This fixes #629
all transformations within the animations should now scale to the right units
[this file](https://asitesol.sharepoint.com/:u:/s/3DRepoTeamFolder/EVgWaWoOMIdEqcvJ3c--S_YBnMHvYzn-W3T4R-N0_2UP0g?e=Y47zmw), which is in ft, has a transformation where some objects moves ~400ft on the x axis. should now work even if model settings has a different units to ft.

ISSUE #629 scale transforms to the right units

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp

This fixes #647 
This PR adds additional checks around the `OdGiMapper`, used to transform UVs when getting the geometry data.
Our use of this is based on the Kernel SDK's ColladaExportView sample.
Previously, we checked for vertex attributes and assumed if they were present, that a mapper would be available, but on some files this is not true. This PR adds a check using the dedicated `isMapperEnabled` and `isMapperAvailable` methods before trying to use it.
Though we checked for attributes before, it is possible the vertex data includes attributes other than UVs - at the moment, ODA has only one possible parameter for the mapping channels, kAllChannels, but just because we can't specify diffuse texture coords, doesn't mine others can't exist.
Another (probably more likely) explanation …

ISSUE #647 Revit file crash

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp
test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo_test_database_info.h
test/src/unit/repo_test_utils.h

This fixes #651 
This bug was caused by ODA outputting an OdGiDrawable for a MEP System Type, for each element connected to a system, where the geometry for an element appeared under the second drawable.
This PR adds a check which ignores any OdGiDrawable that derives from a MEP System Type (`OdBmRbsSystemType`). Since the Geometry Collector is set up by the prior (true) element, ignoring the metadata/geometry collector configuration in `fillMeshData` means the geometry output by the `OdGsBaseMaterialView::draw(pDrawable)` call ends up in the original element, along with its original metadata.
A unit test has been added containing elements for HVAC, Plumbing and Electrical Systems.
#657 should be merged to staging first, as this branch has #647 merged into it so all the imports succeed.
A …

ISSUE 651 - Missing Metadata

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp

This fixes #664
Turns out we already optimise the first level of transformation. The problem lies on the model exporter in the plugins (issue addressed here https://github.com/3drepo/3drepoPlugin/issues/435) - for a node with geometry, it is exporting 2 transformations and a mesh....
To fix any existing .bim files or users using an older version of the plugins, the following change is made here:
- If a node has no name or a transformation, do not port it into 3drepo as a transformation node, instead, append its geometry to the parent of this node.
Test case described in 664 should now function as expected

ISSUE #664 Remove redundant transformation that is preventing metadata from referencing the right object

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_nwd.cpp

This fixes #665
In navisworks importer, added logic keep track on whether we're traversing a composite object, if true, do not change the layer when we're importing geometry.
Also disregard any metadata it may have (they are too low level for users to care - e.g. instanced geometry information)
test case mentioned in the issue should now function as expected

ISSUE #665 Keep composite objects as a single entity in the tree

---

bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo_test_database_info.h
tools/release/git_release.py

This fixes #675
Fixes a bug when Synchro importer sometimes gives us empty UV channels, we are not storing an empty buffer to match but the UV channel is still recorded as > 0
the 2 models in the sharepoint folder should now import successfully.

Issue 675 - do not write UV channel count if we're not writing UVs

---

.travis.yml
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_assimp.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_config.h
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_manager.cpp
client/src/functions.cpp
cmake_modules/FindASSIMPM.cmake
test/src/unit/repo/ut_repo_controller.cpp

This fixes #515
Assimp supported model file rotation is done by file model convertor available in global settings. 
We need to upgrade assimp library to at least 5.X.X version for fetching "GlobalSetting" from assimp file. 
I have done with following assimp branch **https://github.com/assimp/assimp/tree/v5.3.1**

ISSUE #515 FBX rotated on axis

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor_dwg.cpp

This fixes #708 
This PR tells the svg exporter not to explode SHX fonts. SHX fonts have been superseded by TTF fonts in Autodesk products so are unlikely to be encountered.
If they are encountered, this will force the exporter to draw a <text> element without a font-face definition, rather than try to draw  the font as geometry. 
Practically speaking, this PR is just for completeness and should not have much effect so long as we have a complete set of font packages installed in the bouncer containers, which is out of scope of this issue.

ISSUE #703 dont explode fonts into shapes

---

tools/bouncer_worker/src/lib/runCommand.js

This fixes #648 
This PR adds quotations around the exe passed to `spawn`, which allows the name in the config to include spaces. On Linux these are not necessary, but do no harm.

ISSUE #648  path to 3drepobouncerClient executable can have spaces

---

bouncer/src/repo/core/handler/repo_database_handler_mongo.cpp
bouncer/src/repo/core/handler/repo_database_handler_mongo.h
cmake_modules/FindMongoCXXDriver.cmake
test/src/unit/repo/core/handler/ut_repo_database_handler_mongo.cpp

This fixes #723
1. Correctly adds the credentials from the config to the Mongo connection string, if it does not already have any.
2. Masks the credentials, no matter where they came from, when printing the URI to the log in an exception.
Additionally adds unit tests to cover these use cases that were missing before.
regex could be used to mask the username and password, but has an ambiguous feature set (e.g. the positive lookahead operator is not supported) & from comments also possible compiler differences, so given how simple the task is it seemed more robust to do it 'explicitly' with `find`.

ISSUE #723 Mongo database handler properly handles connection string

---

tools/bouncer_worker/config_example.json
tools/bouncer_worker/src/lib/config.js

This fixes #737
- Validation wasn't allowing `elastic` to be undefined in the config as it recycled `envars` definition
- bouncer_worker can now be run without `elastic` being defined
- Run bouncer_worker with `elastic` in config
- Run bouncer_worker without `elastic` in config

ISSUE #737 - Redefine elastic config validation

---

bouncer/src/repo/core/model/bson/repo_bson_builder.cpp

This fixes #755
Recreate the view of the builder that is being appended to if it changes - this is because a view is non-owning and so the builder may move the memory inside the loop.

ISSUE #755 fix for appendElements using view that may be moved

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor_rvt.cpp
test/src/unit/repo/manipulator/modelconvertor/import/odaImport/ut_repo_model_import_oda.cpp

This fixes #776 
This PR makes adjustment to the default view settings for Revit.
The default import view is now `shaded`, instead of `shadedwithedges`, and contour lines are always hidden along with other annotations.
Additionally, only an empty string is now accepted as the view style; invalid strings will throw an exception. There is no new error code for this, because only .io should be setting this parameter via a dropdown.

Issue 776 - Changed default view settings for Revit

---

bouncer/src/repo/core/handler/database/repo_query.h
bouncer/src/repo/core/handler/repo_database_handler_mongo.cpp
bouncer/src/repo/core/model/bson/repo_bson_builder.h
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_manager.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_manager.h
bouncer/src/repo/manipulator/modelutility/repo_scene_builder.cpp
test/src/unit/CMakeLists.txt
test/src/unit/repo/manipulator/modelconvertor/import/odaImport/ut_repo_model_import_oda.cpp
test/src/unit/repo/manipulator/modelconvertor/import/ut_repo_model_import_3drepo.cpp
test/src/unit/repo/manipulator/modelconvertor/import/ut_repo_model_import_ifc.cpp
test/src/unit/repo/manipulator/modelconvertor/import/ut_repo_model_import_synchro.cpp
test/src/unit/repo_test_common_tests.cpp
test/src/unit/repo_test_common_tests.h
test/src/unit/repo_test_scene_utils.cpp
test/src/unit/repo_test_scene_utils.h

This fixes #784
This PR adds a processing stage that ensures any metadata within leaf nodes is hooked up.
Leaf nodes are nodes that have only unnamed meshes as children. For these nodes, any metadata parented to the transform should also be parented to the meshes. This is assumed by the backend when it attempts to resolve external ids from metadata, based on the shared ids passed by the viewer (which will be those of possibly hidden mesh nodes, only).
The use of a processing pass is the best approach because the importers have varying degrees of context. Further if the tree logic can adopt the responsibility of identifying what is and is not a composite object in the future, the processing pass can be removed.
A unit test has been added that can that checks that metadata is correctly …

ISSUE #784 All metadata nodes should be children of their mesh siblings

---

test/src/unit/repo_test_matchers.cpp

This fixes #793
This PR simply updates the version of Googletest to the latest, as the current version is quite old and we are going to get compatibility errors with cmake soon.

Issue 793 - Update googletest

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor_rvt.cpp
test/src/unit/repo/manipulator/modelconvertor/import/odaImport/ut_repo_model_import_oda.cpp

This fixes #795
This PR turns off the Lines category when updating the default view, in order to hide Model entries that are effectively annotations, in keeping with the new expected import behaviour, which is not to import annotations.

ISSUE #795 hide the lines under the Models category, as these are effectively annotations

---

tools/bouncer_worker/src/tasks/imageProcessing.js
tools/bouncer_worker/yarn.lock

This fixes #802 
This task is to change the bouncer worker to call a different tool for converting pdf to svg. Previously, Inkscape was used, but it was found to have horrid performance with big pdfs (see product ticket). This PR now changes it to use [pdf2svg](https://github.com/dawbarton/pdf2svg).

Issue 802 Replace svg converter
