3drepo/3drepobouncer

src/core/handler/repo_abstract_database_handler.h
src/core/handler/repo_mongo_database_handler.cpp
src/core/handler/repo_mongo_database_handler.h
src/core/model/bson/repo_node.cpp
src/test.cpp

Almost silly to be flipping through branches at this point as the functionality is so intertwined. Going to work on master branch until there's a need to branch off.

Issue #2 Merging changes to master

---

bouncer/src/repo/manipulator/repo_manipulator.cpp

- Remove code to generate SRC automatically when importing.

ISSUE #241 remove SRC generation by default

---

bouncer/src/repo/core/model/bson/repo_bson_user.cpp
bouncer/src/repo/manipulator/repo_manipulator.cpp
bouncer/src/repo/manipulator/repo_manipulator.h
bouncer/src/repo/manipulator/statistics/repo_statistics_generator.cpp
bouncer/src/repo/manipulator/statistics/repo_statistics_generator.h
bouncer/src/repo/repo_controller.cpp
bouncer/src/repo/repo_controller.cpp.inl
bouncer/src/repo/repo_controller.h
bouncer/src/repo/repo_controller_internal.cpp.inl
tools/admin/functions.cpp

update to show paid/demo users' statistics separately

Issue 256 - user stats updates

---

bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
bouncer/src/repo/core/model/bson/repo_bson_factory.h
bouncer/src/repo/core/model/bson/repo_bson_unity_assets.h
bouncer/src/repo/core/model/repo_model_global.h
bouncer/src/repo/lib/datastructure/repo_structs.h
bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_asset.cpp
bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_asset.h
bouncer/src/repo/manipulator/modelutility/repo_scene_manager.cpp
bouncer/src/repo/manipulator/repo_manipulator.cpp
bouncer/src/repo/manipulator/repo_manipulator.h
bouncer/src/repo/repo_controller.cpp
bouncer/src/repo/repo_controller.cpp.inl
bouncer/src/repo/repo_controller.h
bouncer/src/repo/repo_controller_internal.cpp.inl

Addresses #265 
Write Unity assets list as BSON to DB.

ISSUE #265 - Write Unity assets list as BSON

---

bouncer/src/repo/core/model/bson/repo_bson_factory.cpp
bouncer/src/repo/core/model/bson/repo_bson_factory.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_dumper.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_dumper.h
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_dgn.cpp
bouncer/src/repo/manipulator/repo_manipulator.cpp

this resolves #271 
**Description**
- Add DGN tree
- Name meshes as their element ID
- Merge meshes together to reduce mesh count
- Catch file read error so it stops crashing when invalid file path is passed 
**Test case**

Issue 271 - DGN tree

---

bouncer/src/repo/manipulator/modeloptimizer/repo_optimizer_multipart.cpp

Early reject if theere is no mesh in the grouping that we're trying to build super mesh with

ISSUE #282 early reject if there's no meshes in group

---

CMakeLists.txt
bouncer/src/repo/core/handler/fileservice/repo_file_handler_s3.cpp
bouncer/src/repo/core/model/collection/repo_scene.cpp
bouncer/src/repo/manipulator/modelutility/repo_scene_cleaner.cpp
bouncer/src/repo/manipulator/modelutility/repo_scene_cleaner.h
bouncer/src/repo/manipulator/modelutility/repo_scene_manager.cpp
bouncer/src/repo/manipulator/repo_manipulator.cpp
test/src/unit/repo/core/handler/fileservice/ut_repo_file_handler_s3.cpp
test/src/unit/repo_test_fileservice_info.h
tools/bouncer_worker/bouncer_worker.js

Addresses #287 
Needs https://github.com/3drepo/3drepo.io/issues/1274

Issue 287 - Turn off S3 storage

---

tools/bouncer_worker/bouncer_worker.js

This is part of the change for 3drepo/3drepo.io#1320

ISSUE #296 Talk to queue directly for callbacks

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor.cpp
bouncer/src/repo/repo_controller.h

Issue 299 - DGN fix

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.h

- Take info about global origin from the model
- Subtract it from min. bounding box when we return the model offset.

Issue 304 - take into account global origin

---

.gitignore
tools/release/git_release.py

Check the script still works on windows and linux

ISSUE 328 - Update git release for OSX and remove git clean

---

bouncer/src/repo/core/handler/fileservice/repo_file_handler_fs.cpp
bouncer/src/repo/core/handler/fileservice/repo_file_manager.cpp
bouncer/src/repo/core/model/collection/repo_scene.cpp
bouncer/src/repo/manipulator/modelutility/repo_scene_manager.cpp
bouncer/src/repo/manipulator/repo_manipulator.cpp
bouncer/src/repo/manipulator/repo_manipulator.h
bouncer/src/repo/repo_controller.cpp
bouncer/src/repo/repo_controller.cpp.inl
bouncer/src/repo/repo_controller.h
bouncer/src/repo/repo_controller_internal.cpp.inl

- We now check if the bad bit is flagged on a ofstream
- return "" (for linkage reference) if it failed
- track and stop the process if it's failed

Issue 335 - Return error and force a failure 

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.h

- BIM v1 should still work
- BIM v2 should work (with 64 bit support)

Issue 332 - support for navisworks plugin update

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/CMakeLists.txt
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/custom_data_util_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/custom_data_util_rvt.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp

we now read and process any custom metadata from rvt

Issue 348 - pull in custom revit metadata

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp

Issue 370 - remove hiddenElementsViewRejection

---

.gitignore
bouncer/src/repo/lib/repo_log.cpp
tools/admin/bouncerTool.cpp
tools/admin/functions.cpp
tools/admin/functions.h
tools/scripts/determineResultFromLog.py
tools/scripts/moveFilesToFolders.py
tools/scripts/runModelTest.py

- added a new option in bouncerTools to run import tests (which doesn't save to db)
- generates a CSV report of passes/failures/timeouts
- put all logs in a folder

Issue 365 test suite to test imports

---

tools/bouncer_worker/bouncer_worker.js

@keifgwinn  can you deploy this somewhere and make sure it fixes the problem with the file?

ISSUE #384 add code to consume the std buffers

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_3drepo.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.h

Issue 421 - Fix for BIM file import when no texture entries exist

---

.travis.yml
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/data_processor_rvt.h
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/file_processor_rvt.cpp
cmake_modules/FindODA.cmake
test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo_test_database_info.h

Issue 424 - upgrade ODA to 2021.12

---

bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.cpp
bouncer/src/repo/manipulator/modelconvertor/import/odaHelper/geometry_collector.h

This fixes #457
changed false to boost optional constructors

ISSUE #457 fix compilation for vc14

---

bouncer/src/repo/manipulator/modelconvertor/export/repo_model_export_src.cpp

This fixes #464.
This PR updates the SRC stash exporter to include texture map information in the multipart mappings Json. The map information is added in a new `textures` array member. The member is optional. The objects added to this array include the UID for the map allowing the texture to be recovered from the web.
Currently, the exporter will only define one map, with a hardcoded type of `diffuse`. This map is detected by looking for nodes that parent to the material's shared Id. This is the same logic used by the AssetBundleCreator.
This PR has no automated tests; it is evaluated through https://github.com/3drepo/3drepoUnreal/issues/31

ISSUE #464 Added texture map information to SRC for textures in Unreal

---

.travis.yml
tools/bouncer_worker/package.json

This fixes #468 
Upgraded to node 14
There should be no difference as before

Issue 468 - upgrade to node 14

---

bouncer/src/repo/core/model/bson/repo_bson.h
test/src/unit/repo/core/model/bson/ut_repo_bson.cpp
test/src/unit/repo/core/model/bson/ut_repo_node.cpp
tools/release/package_release.js

This fixes #435
- Updated gtest to 1.11 (Latest)
- Made a slight change to once class to fix new compilation error in bouncer test
- Waiting on travis

Issue 435: gtest upgrade

---

tools/bouncer_worker/src/lib/elastic.js

This fixes #550 
- changed the method
API key authentication with reduced permissions submits docs successfully.

#550 change from index to create

---

tools/bouncer_worker/package.json
tools/bouncer_worker/src/lib/elastic.js
tools/bouncer_worker/src/lib/utils.js
tools/bouncer_worker/src/queues/modelQueueHandler.js
tools/bouncer_worker/src/queues/unityQueueHandler.js
tools/bouncer_worker/stress.sh

This fixes #552
- added collection of repoLicense to the submitted document.
- repoLicense submitted if available.

ISSUE #552 - add licenseKey to elastic records

---

.travis.yml
cmake_modules/FindSYNCHROREADER.cmake

This fixes #562
compile with v3.0.1 version of the synchro reader

ISSUE #562 synchro version update

---

tools/bouncer_worker/src/lib/processMonitor.js

This fixes #556
- SuAdditional check to see if we are in a license error state before submitting the log
- we shouldn't log to elastic if we have a license failure.

#556 - don't log when in license error state

---

tools/bouncer_worker/src/lib/utils.js
tools/bouncer_worker/src/queues/modelQueueHandler.js
tools/bouncer_worker/src/queues/unityQueueHandler.js

This fixes #569
- Added revision ID to elastic document
- revID

#569 - add rid to documents sent to elastic

---

bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.cpp
bouncer/src/repo/manipulator/modelconvertor/import/repo_model_import_synchro.h

This fixes #603
make resource ID to trans ID a one to many relationship to ensure we are transforming all the entities correctly
https://github.com/3drepo/3drepo.io/issues/4015 should be resolved

ISSUE #603 make resourceID to trans ID a one to many relationship

---

tools/bouncer_worker/src/lib/queueHandler.js
tools/bouncer_worker/src/queues/modelQueueHandler.js

This fixes #614 
- delay inserted in `bouncer_worker`
See issue

ISSUE 614 - Model status doesn't update when you upload a new revision

---

bouncer/src/repo/core/model/bson/repo_bson_user.cpp
bouncer/src/repo/core/model/bson/repo_bson_user.h
bouncer/src/repo/manipulator/modelutility/repo_scene_manager.cpp

This fixes #620
- fetch srcEnabled and vrEnabled from teamspace settings - where it now lives
With srcEnabled, models should now generate srcs again
With vrEnabled, models should now generate win64 and ios bundles again.

ISSUE #620 fetch addon data from the right place

---

.travis.yml
test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo_test_database_info.h

This fixes #633
- use the forked version of OCCT with the fix
- Add a file to test the problem no longer occurs
tests should pass

ISSUE #633 add regression test, update OCCT to fix the issue

---

.travis.yml
ifcUtils/repo_ifc_utils_geometry_handler.cpp

ISSUE #590 Changes for viewing 2D lines in 3Drepo when and IFC file is uploaded.
This fixes #590 
By this changes user can view 2D lines in the 3drepo when he uploads IFC file.

ISSUE 590 - IFC polylines

---

ifcUtils/repo_ifc_utils_geometry_handler.cpp

This fixes #661
disable curve readings so we don't get 2d lines until further notice
IFC import should no longer import lines

ISSUE #661 do not read curves

---

test/src/system/st_3drepobouncerClient.cpp
test/src/unit/repo_test_database_info.h

This fixes #671
Add an importing test case with a synchro 6.5.3.7 file so we know if it errors

ISSUE #671 add synchro 6.5.3.7 test case

---

tools/release/git_release.py

This fixes #673 
Should keep untracked files

ISSUE 673 - do not clean on git_release

---

.travis.yml

This fixes #689 
- Update to asite.com address
- Check inbox for Travis e-mails

ISSUE 689 - Update travis e-mail

---

tools/bouncer_worker/config_example.json
tools/bouncer_worker/src/lib/elastic.js

This fixes #691 
- Add namespace to Elastic record
- Upload a model
- Check Elastic `io-bouncer` records

ISSUE 691 - Add namespace to Elastic record

---

tools/bouncer_worker/package.json

This fixes #701 
- Update elasticsearch
- `io-bouncer` index should update

ISSUE 701 - Elasticsearch upgrade

---

.travis.yml

This fixes #742 
- Upgrade Travis to Mongo 8

ISSUE 742 - Upgrade Travis to Mongo 8

---

.travis.yml
bouncer/src/repo/core/model/bson/repo_bson_builder.cpp
tools/bouncer_worker/package.json
tools/bouncer_worker/yarn.lock
tools/release/package_release.js

This fixes #744
This PR updates the target version of NodeJs and ensures that bouncer_worker and package_release still work.

Issue 744 - Upgrade NodeJs
